name: ExcellCustomer
description: Excell Customer App

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  simple_animations: ^2.2.1
  flutter_spinkit: "^4.1.2"
  pin_code_fields: ^3.0.1
  animated_text_kit: ^2.2.0
  shared_preferences: ^0.5.7+3
  hidden_drawer_menu: ^1.1.4
  fl_chart: ^0.10.0
  toggle_switch: "^0.1.4"
  date_format: ^1.0.8  
  bot_toast: ^3.0.0
  flutter_typeahead: ^1.8.3


  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf

  uses-material-design: true
  assets:
    - assets/

