name: ExcellCustomer
description: Excell Customer App

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  loading: ^1.0.2
  localstorage: ^3.0.2+5
  carousel_slider: ^2.0.0
  fluttertoast: ^4.0.1
  font_awesome_flutter: ^8.8.1
  pin_code_fields: ^2.5.1
  percent_indicator: ^2.1.3
  date_format: ^1.0.8
  solid_bottom_sheet: ^0.1.9
  firebase_core: ^0.4.0+9
  firebase_messaging: ^6.0.13
  flutter_local_notifications: ^1.4.1
  charts_flutter: ^0.9.0
  flutter_svg: ^0.17.1

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/

